name: Update some list

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  watch:
    types: [started]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: generator
        uses: simonecorsi/mawesome@v2
        with:
          api-token: ${{ secrets.API_TOKEN }}
          github-email: ${{ secrets.USER_EMAIL }}
          template-path: "template/README.ejs"
          output-filename: "data.md"
          github-name: ${{ github.repository_owner }}
